---
title: "#3 - Help with grant informatics infrastructure language"
format: 
  html:
    toc: true
    toc-location: right
author: Ran Li
---

# Request

## Issue

> <https://github.com/Drexel-UHC/analytics-core/issues/3>
>
> I am working with Ana Diez Roux and Jane Clougherty to write a grant proposing that we at Drexel be the Research Coordinating Center for a Climate Change and Health Community of Practice. The grant would **provide funding to do many of the things that folks at the UHC are doing for SALURBAL**, including providing "high-security-compliant, high-capacity informatics infrastructure suitable for data integration, storage, management, and sharing and ensure that the data meet the FAIR principles: findability, accessibility, interoperability, and reusability." While we are doing this for several projects across our groups, **I am having a hard time describing the first part (high-security-compliant, high-capacity informatics infrastructure suitable for data integration, storage, management, and sharing)**. Ana suggested I reach out to you to see if you could help us draft some language that describes how we do this?

## First Impressions


The key pieces of information that stuck out to me are bold in the request above. The request is for language to describe the following things:

- **high-security-compliant**
- **high-capacity informatics infrastructure** suitable for data
  - **integration**
  - **storage**
  - **management**
  - **sharing**

Some random thoughts:

- THe technical jargon may be 

## Action Item



Below we will document firstly the informatics infrastructure we utilize for SALURBAL and secondly talk about the high security compliance of said infrastructure.

# SALURBAL - Informatic Infratrastructure

What is informatics infrastructure. \## High Capacity informatics infrastructure I think the key thing here is to formalize what we have been doing with SALURBAL which is an ETL pipeline. However I think its best we present this within the scope of perhaps other informatics infrastructures (I'm jsut throwing buzzwords out here: traditional databases, lakes, warehouses); we need to first define them briefly.

## High security compliant

Talking points to mention - ETL pipeline - Already established
