---
title: "Datawarehousing with DBT"
subtitle: Notes and resources 
---

This will be a series of 1 hour collaborative coding sessions where we will learn to use DBT to build a data warehouse. This will be extremely informal and will be a safe space to ask questions and learn together. The rough outline of the series is as follows:

-   Session 1 (5/10/23): [Get Started + Setup](https://drexel-uhc.github.io/analytics-corner/pages/manuals/dbt/get-started-install.html)
    -   setup software required for DBT
-   Session 2 (5/24/23): [Loading data into DBT](https://drexel-uhc.github.io/analytics-corner/pages/manuals/dbt/load-data.html)
    -   Start with source data (.csv or .parquet or .json)
    -   Load source data into DBT
    -   Generate documentation
-   Session 3 (5/31/23): Intro to Modeling
    -   Intro to structure
    -   Base models
    -   Interactive modeling
-   Session 4 (6/7/23): Data Modeling + Documentation
    -   Intermediate and Mart layers
    -   Documentation with doc blocks
-   Session 5 (6/14/23): Intermediate Features
    -   Macros
    -   Testing
    -   Working on the cloud
    -   Customizing DBT

------------------------------------------------------------------------

::: callout-note
**Somethings to keep in mind before we start**

-   The learning/teaching process may be difficult so don't feel like you aren't picking things up quickly enough; this is normal. Be patient with yourself and the instructor.

-   Learning this workflow is a case of slowing down to really really speed up. Thanks for being here!

-   This course is not a comprehensive guide to data warehousing with DBT but rather meant to get you started in terms of software and introduce basic concepts. Please see the following for more resources to help you learn.

    -   [dbt fundamentals](https://courses.getdbt.com/courses/fundamentals)

    -   [dbt Jinja, Macros, Packages](https://courses.getdbt.com/courses/jinja-macros-packages)

    -   [Refactoring SQL for Modularity](https://courses.getdbt.com/courses/refactoring-sql-for-modularity)

    -   [DBT Courses (All)](https://courses.getdbt.com/collections)

    -   Note, these courses DBT cloud but you can use the set up we introduce to practice
:::
