---
title: "Frequently Asked Questions"
comments:
  hypothesis: true
---

:::{.callout-note}
The analytics corner is not official in any capacity and is just a proof of concept. The language language is still being drafted and a work in progress. Feel free to Edit this page or report an issue.
:::


### What is the Analytics Corner?

Build bridges at the UHC by open sourcing your analytic problems. 

 

### How do I submit an issue?

Please click on the button below to start a intake form which will generate a GitHub issue for you. Don't forget to enter a title in your issue. Also all form inputs that have red asterisks require answers before the issue can be submitted. Please email rl627@drexel.edu if you have any questions or trouble submitting an issue.

### What is GitHub?

GitHub is a online host for version control, project management and collaborative development. We have found it extremely useful in managing complex projects, sharing reproducible work/data and building bridges while working remotely. For academics it's premium features are completely free. You can sign up at https://github.com/join; note, try to use your real name if you can and it is encouraged to upload a profile pic.

### How can I contribute?

You can contribute by participating in discussions, opening issues or submiting Pull Requests to address open issues. 


